### ISSUE TITLE
Allow cop to be hosted from an offline server

### ISSUE THREAD

**Issue by stevewillson** [psmitty7373/ctfcop#1]
There are references to external resources that require an internet connection.

The Bootstrap darkly theme references external resources.
https://fonts.googleapis.com/css?family=Lato:400,700,400italic

https://webmasters.stackexchange.com/questions/109337/how-do-i-use-bootstraps-darkly-theme-without-external-references

**Comment by psmitty7373** [comment]
Was not using the italics anyway, so I just  removed them altogether.  Thank you!
